export const MOCK_XCHANGE_DATA = `
<SportsMXFData>
  <SportsMetadataSchema>Copyright 2007-2013 Sports Video Interoperability Group, Inc.</SportsMetadataSchema>
  <MetadataVersion>2.1</MetadataVersion>
  <FileName>24 2151 01-20-25 INND K VS OHST.mp4</FileName>
  <Games>
    <Game>
      <Sport>Football</Sport>
      <TotalPlayCount>23</TotalPlayCount>
    </Game>
  </Games>
  <Plays>
    <Play>
      <FullSequence>1</FullSequence>
      <PlayNumber>1</PlayNumber>
      <Down>1</Down>
      <Distance>10</Distance>
      <Yardline>25</Yardline>
      <Quarter>1</Quarter>
      <Series>1</Series>
      <Gain>5</Gain>
      <Views>
        <View><MarkIn>2</MarkIn><Duration>106</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>113</MarkIn><Duration>1367</Duration><CameraView>SL</CameraView></View>
        <View><MarkIn>1485</MarkIn><Duration>1247</Duration><CameraView>EZ</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>2</FullSequence>
      <PlayNumber>2</PlayNumber>
      <Down>2</Down>
      <Distance>5</Distance>
      <Yardline>30</Yardline>
      <Quarter>1</Quarter>
      <Gain>3</Gain>
      <Views>
        <View><MarkIn>2737</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>2849</MarkIn><Duration>1027</Duration><CameraView>SL</CameraView></View>
        <View><MarkIn>3881</MarkIn><Duration>1167</Duration><CameraView>EZ</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>3</FullSequence>
      <PlayNumber>3</PlayNumber>
      <Down>3</Down>
      <Distance>2</Distance>
      <Yardline>33</Yardline>
      <Quarter>1</Quarter>
      <Gain>15</Gain>
      <Views>
        <View><MarkIn>5053</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>5165</MarkIn><Duration>1137</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>4</FullSequence>
      <PlayNumber>4</PlayNumber>
      <Down>1</Down>
      <Distance>10</Distance>
      <Yardline>48</Yardline>
      <Quarter>1</Quarter>
      <Gain>0</Gain>
      <Views>
        <View><MarkIn>7539</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>7651</MarkIn><Duration>1207</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>5</FullSequence>
      <PlayNumber>5</PlayNumber>
      <Down>2</Down>
      <Distance>10</Distance>
      <Yardline>48</Yardline>
      <Quarter>1</Quarter>
      <Gain>8</Gain>
      <Views>
        <View><MarkIn>10215</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>10327</MarkIn><Duration>1497</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>6</FullSequence>
      <PlayNumber>6</PlayNumber>
      <Down>3</Down>
      <Distance>2</Distance>
      <Yardline>40</Yardline>
      <Quarter>1</Quarter>
      <Gain>4</Gain>
      <Views>
        <View><MarkIn>13445</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>13557</MarkIn><Duration>1367</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>7</FullSequence>
      <PlayNumber>7</PlayNumber>
      <Down>1</Down>
      <Distance>10</Distance>
      <Yardline>36</Yardline>
      <Quarter>1</Quarter>
      <Gain>-2</Gain>
      <Views>
        <View><MarkIn>16239</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>16351</MarkIn><Duration>1437</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>8</FullSequence>
      <PlayNumber>8</PlayNumber>
      <Down>2</Down>
      <Distance>12</Distance>
      <Yardline>38</Yardline>
      <Quarter>1</Quarter>
      <Gain>12</Gain>
      <Views>
        <View><MarkIn>19295</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>19407</MarkIn><Duration>1417</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>9</FullSequence>
      <PlayNumber>9</PlayNumber>
      <Down>1</Down>
      <Distance>10</Distance>
      <Yardline>26</Yardline>
      <Quarter>1</Quarter>
      <Gain>5</Gain>
      <Views>
        <View><MarkIn>22331</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>22443</MarkIn><Duration>1367</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>10</FullSequence>
      <PlayNumber>10</PlayNumber>
      <Down>2</Down>
      <Distance>5</Distance>
      <Yardline>21</Yardline>
      <Quarter>1</Quarter>
      <Gain>21</Gain>
      <Views>
        <View><MarkIn>25167</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>25279</MarkIn><Duration>1417</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>11</FullSequence>
      <PlayNumber>11</PlayNumber>
      <Down>1</Down>
      <Distance>10</Distance>
      <Yardline>3</Yardline>
      <Quarter>2</Quarter>
      <Gain>0</Gain>
      <Views>
        <View><MarkIn>28113</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>28225</MarkIn><Duration>1097</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>12</FullSequence>
      <PlayNumber>12</PlayNumber>
      <Down>2</Down>
      <Distance>10</Distance>
      <Yardline>3</Yardline>
      <Quarter>2</Quarter>
      <Gain>0</Gain>
      <Views>
        <View><MarkIn>31099</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>31211</MarkIn><Duration>1209</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>13</FullSequence>
      <PlayNumber>13</PlayNumber>
      <Down>3</Down>
      <Distance>10</Distance>
      <Yardline>3</Yardline>
      <Quarter>2</Quarter>
      <Gain>0</Gain>
      <Views>
        <View><MarkIn>33517</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>33629</MarkIn><Duration>1027</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>14</FullSequence>
      <PlayNumber>14</PlayNumber>
      <Down>4</Down>
      <Distance>10</Distance>
      <Yardline>3</Yardline>
      <Quarter>2</Quarter>
      <Gain>0</Gain>
      <Views>
        <View><MarkIn>35703</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>35815</MarkIn><Duration>775</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>15</FullSequence>
      <PlayNumber>15</PlayNumber>
      <Down>1</Down>
      <Distance>10</Distance>
      <Yardline>20</Yardline>
      <Quarter>2</Quarter>
      <Gain>8</Gain>
      <Views>
        <View><MarkIn>37817</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>37929</MarkIn><Duration>1343</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>16</FullSequence>
      <PlayNumber>16</PlayNumber>
      <Down>2</Down>
      <Distance>2</Distance>
      <Yardline>28</Yardline>
      <Quarter>2</Quarter>
      <Gain>3</Gain>
      <Views>
        <View><MarkIn>40709</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>40821</MarkIn><Duration>897</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>17</FullSequence>
      <PlayNumber>17</PlayNumber>
      <Down>1</Down>
      <Distance>10</Distance>
      <Yardline>31</Yardline>
      <Quarter>2</Quarter>
      <Gain>5</Gain>
      <Views>
        <View><MarkIn>42805</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>42917</MarkIn><Duration>1037</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>18</FullSequence>
      <PlayNumber>18</PlayNumber>
      <Down>2</Down>
      <Distance>5</Distance>
      <Yardline>36</Yardline>
      <Quarter>2</Quarter>
      <Gain>6</Gain>
      <Views>
        <View><MarkIn>44901</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>45013</MarkIn><Duration>1067</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>19</FullSequence>
      <PlayNumber>19</PlayNumber>
      <Down>1</Down>
      <Distance>10</Distance>
      <Yardline>42</Yardline>
      <Quarter>2</Quarter>
      <Gain>12</Gain>
      <Views>
        <View><MarkIn>47037</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>47149</MarkIn><Duration>957</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>20</FullSequence>
      <PlayNumber>20</PlayNumber>
      <Down>1</Down>
      <Distance>10</Distance>
      <Yardline>46</Yardline>
      <Quarter>2</Quarter>
      <Gain>4</Gain>
      <Views>
        <View><MarkIn>49273</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>49385</MarkIn><Duration>917</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>21</FullSequence>
      <PlayNumber>21</PlayNumber>
      <Down>2</Down>
      <Distance>6</Distance>
      <Yardline>42</Yardline>
      <Quarter>2</Quarter>
      <Gain>5</Gain>
      <Views>
        <View><MarkIn>51369</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>51481</MarkIn><Duration>977</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>22</FullSequence>
      <PlayNumber>22</PlayNumber>
      <Down>3</Down>
      <Distance>1</Distance>
      <Yardline>37</Yardline>
      <Quarter>2</Quarter>
      <Gain>2</Gain>
      <Views>
        <View><MarkIn>53525</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>53637</MarkIn><Duration>1087</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
    <Play>
      <FullSequence>23</FullSequence>
      <PlayNumber>23</PlayNumber>
      <Down>1</Down>
      <Distance>10</Distance>
      <Yardline>35</Yardline>
      <Quarter>2</Quarter>
      <Gain>0</Gain>
      <Views>
        <View><MarkIn>55931</MarkIn><Duration>107</Duration><CameraView>SB</CameraView></View>
        <View><MarkIn>56043</MarkIn><Duration>1177</Duration><CameraView>SL</CameraView></View>
      </Views>
    </Play>
  </Plays>
</SportsMXFData>
`
