/**
 * Mock Games Data
 * 
 * Contains realistic NFL, College, and High School game data that clips can reference.
 * Games serve as the parent container for clips.
 */

import type { Game, GameStatus, GameWeather, BroadcastInfo, GameScore, GameLeague } from "@/types/game"

// ---------------------------------------------------------------------------
// Mock Games
// ---------------------------------------------------------------------------

export const mockGames: Game[] = [
  // ---------------------------------------------------------------------------
  // NFL Games (10 games)
  // ---------------------------------------------------------------------------
  
  // Week 11 Games (2024 Season)
  {
    id: "game-001",
    league: "NFL",
    homeTeamId: "kc",
    awayTeamId: "buf",
    date: "2024-11-17",
    kickoffTime: "16:25",
    season: "2024",
    week: 11,
    gameType: "regular",
    status: "final",
    score: {
      home: 21,
      away: 30,
      quarters: {
        q1: { home: 7, away: 10 },
        q2: { home: 7, away: 6 },
        q3: { home: 0, away: 7 },
        q4: { home: 7, away: 7 },
      },
    },
    venue: "GEHA Field at Arrowhead Stadium",
    city: "Kansas City, MO",
    weather: { temperature: 45, condition: "cloudy", windSpeed: 12, humidity: 65 },
    attendance: 76416,
    broadcast: { network: "CBS", announcers: ["Jim Nantz", "Tony Romo"] },
    matchupDisplay: "BUF @ KC",
  },
  {
    id: "game-002",
    league: "NFL",
    homeTeamId: "chi",
    awayTeamId: "gb",
    date: "2024-11-17",
    kickoffTime: "13:00",
    season: "2024",
    week: 11,
    gameType: "regular",
    status: "final",
    score: {
      home: 19,
      away: 38,
      quarters: {
        q1: { home: 3, away: 14 },
        q2: { home: 10, away: 10 },
        q3: { home: 0, away: 7 },
        q4: { home: 6, away: 7 },
      },
    },
    venue: "Soldier Field",
    city: "Chicago, IL",
    weather: { temperature: 38, condition: "windy", windSpeed: 22, humidity: 55 },
    attendance: 61500,
    broadcast: { network: "FOX", announcers: ["Kevin Burkhardt", "Tom Brady"] },
    matchupDisplay: "GB @ CHI",
  },
  {
    id: "game-003",
    league: "NFL",
    homeTeamId: "bal",
    awayTeamId: "pit",
    date: "2024-11-17",
    kickoffTime: "13:00",
    season: "2024",
    week: 11,
    gameType: "regular",
    status: "final",
    score: {
      home: 28,
      away: 14,
      quarters: {
        q1: { home: 7, away: 7 },
        q2: { home: 14, away: 0 },
        q3: { home: 0, away: 7 },
        q4: { home: 7, away: 0 },
      },
    },
    venue: "M&T Bank Stadium",
    city: "Baltimore, MD",
    weather: { temperature: 52, condition: "clear", windSpeed: 8, humidity: 45 },
    attendance: 71008,
    broadcast: { network: "CBS", announcers: ["Ian Eagle", "Charles Davis"] },
    matchupDisplay: "PIT @ BAL",
  },
  {
    id: "game-004",
    league: "NFL",
    homeTeamId: "dal",
    awayTeamId: "sf",
    date: "2024-11-17",
    kickoffTime: "20:20",
    season: "2024",
    week: 11,
    gameType: "regular",
    status: "final",
    score: {
      home: 17,
      away: 24,
      quarters: {
        q1: { home: 0, away: 7 },
        q2: { home: 10, away: 10 },
        q3: { home: 0, away: 0 },
        q4: { home: 7, away: 7 },
      },
    },
    venue: "AT&T Stadium",
    city: "Arlington, TX",
    weather: { temperature: 72, condition: "dome" },
    attendance: 93584,
    broadcast: { network: "NBC", announcers: ["Mike Tirico", "Cris Collinsworth"] },
    matchupDisplay: "SF @ DAL",
  },
  {
    id: "game-005",
    league: "NFL",
    homeTeamId: "nyg",
    awayTeamId: "phi",
    date: "2024-11-17",
    kickoffTime: "13:00",
    season: "2024",
    week: 11,
    gameType: "regular",
    status: "final",
    score: {
      home: 7,
      away: 28,
      quarters: {
        q1: { home: 0, away: 14 },
        q2: { home: 7, away: 7 },
        q3: { home: 0, away: 0 },
        q4: { home: 0, away: 7 },
      },
    },
    venue: "MetLife Stadium",
    city: "East Rutherford, NJ",
    weather: { temperature: 48, condition: "cloudy", windSpeed: 10, humidity: 60 },
    attendance: 82500,
    broadcast: { network: "FOX", announcers: ["Joe Davis", "Greg Olsen"] },
    matchupDisplay: "PHI @ NYG",
  },
  {
    id: "game-006",
    league: "NFL",
    homeTeamId: "min",
    awayTeamId: "det",
    date: "2024-11-17",
    kickoffTime: "13:00",
    season: "2024",
    week: 11,
    gameType: "regular",
    status: "final",
    score: {
      home: 24,
      away: 31,
      quarters: {
        q1: { home: 7, away: 10 },
        q2: { home: 10, away: 7 },
        q3: { home: 0, away: 7 },
        q4: { home: 7, away: 7 },
      },
    },
    venue: "U.S. Bank Stadium",
    city: "Minneapolis, MN",
    weather: { temperature: 72, condition: "dome" },
    attendance: 66860,
    broadcast: { network: "FOX", announcers: ["Adam Amin", "Mark Schlereth"] },
    matchupDisplay: "DET @ MIN",
  },
  {
    id: "game-007",
    league: "NFL",
    homeTeamId: "det",
    awayTeamId: "chi",
    date: "2024-11-28",
    kickoffTime: "12:30",
    season: "2024",
    week: 12,
    gameType: "regular",
    status: "final",
    score: {
      home: 23,
      away: 20,
      quarters: {
        q1: { home: 6, away: 7 },
        q2: { home: 7, away: 6 },
        q3: { home: 7, away: 0 },
        q4: { home: 3, away: 7 },
      },
    },
    venue: "Ford Field",
    city: "Detroit, MI",
    weather: { temperature: 72, condition: "dome" },
    attendance: 65000,
    broadcast: { network: "CBS", announcers: ["Jim Nantz", "Tony Romo"] },
    matchupDisplay: "CHI @ DET",
  },
  {
    id: "game-008",
    league: "NFL",
    homeTeamId: "mia",
    awayTeamId: "nyj",
    date: "2024-11-24",
    kickoffTime: "13:00",
    season: "2024",
    week: 12,
    gameType: "regular",
    status: "final",
    score: {
      home: 32,
      away: 26,
      quarters: {
        q1: { home: 10, away: 3 },
        q2: { home: 7, away: 10 },
        q3: { home: 8, away: 6 },
        q4: { home: 7, away: 7 },
      },
    },
    venue: "Hard Rock Stadium",
    city: "Miami Gardens, FL",
    weather: { temperature: 78, condition: "clear", windSpeed: 5, humidity: 70 },
    attendance: 65326,
    broadcast: { network: "CBS", announcers: ["Ian Eagle", "Charles Davis"] },
    matchupDisplay: "NYJ @ MIA",
  },
  {
    id: "game-009",
    league: "NFL",
    homeTeamId: "buf",
    awayTeamId: "sf",
    date: "2024-12-01",
    kickoffTime: "20:20",
    season: "2024",
    week: 13,
    gameType: "regular",
    status: "scheduled",
    venue: "Highmark Stadium",
    city: "Orchard Park, NY",
    weather: { temperature: 35, condition: "snow", windSpeed: 15, humidity: 80 },
    broadcast: { network: "NBC", announcers: ["Mike Tirico", "Cris Collinsworth"] },
    matchupDisplay: "SF @ BUF",
  },
  {
    id: "game-010",
    league: "NFL",
    homeTeamId: "kc",
    awayTeamId: "lv",
    date: "2024-11-29",
    kickoffTime: "15:00",
    season: "2024",
    week: 13,
    gameType: "regular",
    status: "scheduled",
    venue: "GEHA Field at Arrowhead Stadium",
    city: "Kansas City, MO",
    broadcast: { network: "Amazon Prime", announcers: ["Al Michaels", "Kirk Herbstreit"] },
    matchupDisplay: "LV @ KC",
  },

  // ---------------------------------------------------------------------------
  // College Football Games (10 games)
  // ---------------------------------------------------------------------------

  {
    id: "college-001",
    league: "College",
    homeTeamId: "geo",
    awayTeamId: "ala",
    date: "2024-11-16",
    kickoffTime: "15:30",
    season: "2024",
    week: 12,
    gameType: "regular",
    status: "final",
    score: { home: 28, away: 21, quarters: { q1: { home: 7, away: 7 }, q2: { home: 7, away: 7 }, q3: { home: 7, away: 0 }, q4: { home: 7, away: 7 } } },
    venue: "Sanford Stadium",
    city: "Athens, GA",
    weather: { temperature: 58, condition: "clear", windSpeed: 8, humidity: 55 },
    attendance: 92746,
    broadcast: { network: "CBS", announcers: ["Brad Nessler", "Gary Danielson"] },
    matchupDisplay: "ALA @ UGA",
  },
  {
    id: "college-002",
    league: "College",
    homeTeamId: "tex",
    awayTeamId: "okl",
    date: "2024-10-12",
    kickoffTime: "12:00",
    season: "2024",
    week: 7,
    gameType: "regular",
    status: "final",
    score: { home: 34, away: 30, quarters: { q1: { home: 10, away: 7 }, q2: { home: 7, away: 10 }, q3: { home: 10, away: 6 }, q4: { home: 7, away: 7 } } },
    venue: "Cotton Bowl",
    city: "Dallas, TX",
    weather: { temperature: 72, condition: "clear", windSpeed: 5, humidity: 40 },
    attendance: 92100,
    broadcast: { network: "ABC", announcers: ["Chris Fowler", "Kirk Herbstreit"] },
    matchupDisplay: "OKL @ TEX",
  },
  {
    id: "college-003",
    league: "College",
    homeTeamId: "lsu",
    awayTeamId: "fla",
    date: "2024-11-09",
    kickoffTime: "19:00",
    season: "2024",
    week: 11,
    gameType: "regular",
    status: "final",
    score: { home: 42, away: 28, quarters: { q1: { home: 14, away: 7 }, q2: { home: 7, away: 14 }, q3: { home: 14, away: 0 }, q4: { home: 7, away: 7 } } },
    venue: "Tiger Stadium",
    city: "Baton Rouge, LA",
    weather: { temperature: 65, condition: "clear", windSpeed: 10, humidity: 70 },
    attendance: 102321,
    broadcast: { network: "ESPN", announcers: ["Joe Tessitore", "Jesse Palmer"] },
    matchupDisplay: "FLA @ LSU",
  },
  {
    id: "college-004",
    league: "College",
    homeTeamId: "aub",
    awayTeamId: "tenn",
    date: "2024-11-02",
    kickoffTime: "15:30",
    season: "2024",
    week: 10,
    gameType: "regular",
    status: "final",
    score: { home: 17, away: 24, quarters: { q1: { home: 3, away: 7 }, q2: { home: 7, away: 10 }, q3: { home: 0, away: 0 }, q4: { home: 7, away: 7 } } },
    venue: "Jordan-Hare Stadium",
    city: "Auburn, AL",
    weather: { temperature: 62, condition: "cloudy", windSpeed: 12, humidity: 60 },
    attendance: 87451,
    broadcast: { network: "CBS", announcers: ["Brad Nessler", "Gary Danielson"] },
    matchupDisplay: "TENN @ AUB",
  },
  {
    id: "college-005",
    league: "College",
    homeTeamId: "osu",
    awayTeamId: "mich",
    date: "2024-11-30",
    kickoffTime: "12:00",
    season: "2024",
    week: 14,
    gameType: "regular",
    status: "final",
    score: { home: 13, away: 10, quarters: { q1: { home: 3, away: 0 }, q2: { home: 3, away: 7 }, q3: { home: 0, away: 3 }, q4: { home: 7, away: 0 } } },
    venue: "Ohio Stadium",
    city: "Columbus, OH",
    weather: { temperature: 35, condition: "snow", windSpeed: 15, humidity: 75 },
    attendance: 105708,
    broadcast: { network: "FOX", announcers: ["Gus Johnson", "Joel Klatt"] },
    matchupDisplay: "MICH @ OSU",
  },
  {
    id: "college-006",
    league: "College",
    homeTeamId: "psu",
    awayTeamId: "ore",
    date: "2024-10-19",
    kickoffTime: "19:30",
    season: "2024",
    week: 8,
    gameType: "regular",
    status: "final",
    score: { home: 31, away: 35, quarters: { q1: { home: 7, away: 14 }, q2: { home: 10, away: 7 }, q3: { home: 7, away: 7 }, q4: { home: 7, away: 7 } } },
    venue: "Beaver Stadium",
    city: "State College, PA",
    weather: { temperature: 52, condition: "cloudy", windSpeed: 8, humidity: 50 },
    attendance: 110823,
    broadcast: { network: "NBC", announcers: ["Noah Eagle", "Todd Blackledge"] },
    matchupDisplay: "ORE @ PSU",
  },
  {
    id: "college-007",
    league: "College",
    homeTeamId: "usc",
    awayTeamId: "ucla",
    date: "2024-11-23",
    kickoffTime: "20:00",
    season: "2024",
    week: 13,
    gameType: "regular",
    status: "final",
    score: { home: 27, away: 24, quarters: { q1: { home: 7, away: 10 }, q2: { home: 10, away: 7 }, q3: { home: 3, away: 0 }, q4: { home: 7, away: 7 } } },
    venue: "Los Angeles Memorial Coliseum",
    city: "Los Angeles, CA",
    weather: { temperature: 68, condition: "clear", windSpeed: 5, humidity: 35 },
    attendance: 77500,
    broadcast: { network: "ABC", announcers: ["Sean McDonough", "Greg McElroy"] },
    matchupDisplay: "UCLA @ USC",
  },
  {
    id: "college-008",
    league: "College",
    homeTeamId: "wis",
    awayTeamId: "iowa",
    date: "2024-11-09",
    kickoffTime: "12:00",
    season: "2024",
    week: 11,
    gameType: "regular",
    status: "final",
    score: { home: 14, away: 10, quarters: { q1: { home: 0, away: 3 }, q2: { home: 7, away: 0 }, q3: { home: 0, away: 7 }, q4: { home: 7, away: 0 } } },
    venue: "Camp Randall Stadium",
    city: "Madison, WI",
    weather: { temperature: 42, condition: "windy", windSpeed: 20, humidity: 55 },
    attendance: 80321,
    broadcast: { network: "BTN", announcers: ["Kevin Kugler", "Matt Millen"] },
    matchupDisplay: "IOWA @ WIS",
  },
  {
    id: "college-009",
    league: "College",
    homeTeamId: "colo",
    awayTeamId: "utahst",
    date: "2024-11-16",
    kickoffTime: "14:00",
    season: "2024",
    week: 12,
    gameType: "regular",
    status: "final",
    score: { home: 28, away: 31, quarters: { q1: { home: 7, away: 7 }, q2: { home: 14, away: 10 }, q3: { home: 0, away: 7 }, q4: { home: 7, away: 7 } } },
    venue: "Folsom Field",
    city: "Boulder, CO",
    weather: { temperature: 45, condition: "clear", windSpeed: 10, humidity: 25 },
    attendance: 54321,
    broadcast: { network: "FOX", announcers: ["Jason Benetti", "Brock Huard"] },
    matchupDisplay: "UTAH @ COLO",
  },
  {
    id: "college-010",
    league: "College",
    homeTeamId: "tcu",
    awayTeamId: "byu",
    date: "2024-10-26",
    kickoffTime: "19:00",
    season: "2024",
    week: 9,
    gameType: "regular",
    status: "final",
    score: { home: 21, away: 24, quarters: { q1: { home: 7, away: 7 }, q2: { home: 0, away: 10 }, q3: { home: 7, away: 0 }, q4: { home: 7, away: 7 } } },
    venue: "Amon G. Carter Stadium",
    city: "Fort Worth, TX",
    weather: { temperature: 70, condition: "clear", windSpeed: 8, humidity: 45 },
    attendance: 47000,
    broadcast: { network: "ESPN", announcers: ["Dave Flemming", "Rod Gilmore"] },
    matchupDisplay: "BYU @ TCU",
  },

  // ---------------------------------------------------------------------------
  // High School Football Games (10 games)
  // ---------------------------------------------------------------------------

  {
    id: "hs-001",
    league: "HighSchool",
    homeTeamId: "hs-southlake",
    awayTeamId: "hs-allen",
    date: "2024-11-15",
    kickoffTime: "19:00",
    season: "2024",
    week: 11,
    gameType: "playoff",
    status: "final",
    score: { home: 35, away: 28, quarters: { q1: { home: 7, away: 7 }, q2: { home: 14, away: 7 }, q3: { home: 7, away: 7 }, q4: { home: 7, away: 7 } } },
    venue: "Dragon Stadium",
    city: "Southlake, TX",
    weather: { temperature: 62, condition: "clear", windSpeed: 8, humidity: 50 },
    attendance: 12000,
    broadcast: { network: "NFHS Network" },
    matchupDisplay: "ALLE @ SLC",
  },
  {
    id: "hs-002",
    league: "HighSchool",
    homeTeamId: "hs-north-shore",
    awayTeamId: "hs-katy",
    date: "2024-11-22",
    kickoffTime: "19:30",
    season: "2024",
    week: 12,
    gameType: "playoff",
    status: "final",
    score: { home: 42, away: 35, quarters: { q1: { home: 14, away: 7 }, q2: { home: 7, away: 14 }, q3: { home: 14, away: 7 }, q4: { home: 7, away: 7 } } },
    venue: "Galena Park ISD Stadium",
    city: "Galena Park, TX",
    weather: { temperature: 68, condition: "clear", windSpeed: 5, humidity: 60 },
    attendance: 15000,
    broadcast: { network: "Bally Sports" },
    matchupDisplay: "KATY @ NSM",
  },
  {
    id: "hs-003",
    league: "HighSchool",
    homeTeamId: "hs-duncanville",
    awayTeamId: "hs-westlake",
    date: "2024-12-07",
    kickoffTime: "14:00",
    season: "2024",
    week: 15,
    gameType: "playoff",
    status: "final",
    score: { home: 24, away: 31, quarters: { q1: { home: 7, away: 10 }, q2: { home: 7, away: 7 }, q3: { home: 3, away: 7 }, q4: { home: 7, away: 7 } } },
    venue: "Panther Stadium",
    city: "Duncanville, TX",
    weather: { temperature: 55, condition: "cloudy", windSpeed: 12, humidity: 55 },
    attendance: 10000,
    broadcast: { network: "NFHS Network" },
    matchupDisplay: "WLC @ DUN",
  },
  {
    id: "hs-004",
    league: "HighSchool",
    homeTeamId: "hs-katy",
    awayTeamId: "hs-allen",
    date: "2024-10-18",
    kickoffTime: "19:00",
    season: "2024",
    week: 8,
    gameType: "regular",
    status: "final",
    score: { home: 28, away: 21, quarters: { q1: { home: 7, away: 7 }, q2: { home: 7, away: 7 }, q3: { home: 7, away: 0 }, q4: { home: 7, away: 7 } } },
    venue: "Legacy Stadium",
    city: "Katy, TX",
    weather: { temperature: 72, condition: "clear", windSpeed: 5, humidity: 55 },
    attendance: 14000,
    broadcast: { network: "NFHS Network" },
    matchupDisplay: "ALLE @ KATY",
  },
  {
    id: "hs-005",
    league: "HighSchool",
    homeTeamId: "hs-mater-dei",
    awayTeamId: "hs-st-john-bosco",
    date: "2024-10-11",
    kickoffTime: "19:30",
    season: "2024",
    week: 7,
    gameType: "regular",
    status: "final",
    score: { home: 28, away: 24, quarters: { q1: { home: 7, away: 7 }, q2: { home: 7, away: 10 }, q3: { home: 7, away: 0 }, q4: { home: 7, away: 7 } } },
    venue: "Santa Ana Stadium",
    city: "Santa Ana, CA",
    weather: { temperature: 75, condition: "clear", windSpeed: 5, humidity: 40 },
    attendance: 8500,
    broadcast: { network: "Bally Sports" },
    matchupDisplay: "SJB @ MDM",
  },
  {
    id: "hs-006",
    league: "HighSchool",
    homeTeamId: "hs-de-la-salle",
    awayTeamId: "hs-serra",
    date: "2024-11-01",
    kickoffTime: "19:00",
    season: "2024",
    week: 10,
    gameType: "regular",
    status: "final",
    score: { home: 35, away: 14, quarters: { q1: { home: 14, away: 0 }, q2: { home: 7, away: 7 }, q3: { home: 7, away: 0 }, q4: { home: 7, away: 7 } } },
    venue: "Owen Owens Field",
    city: "Concord, CA",
    weather: { temperature: 62, condition: "cloudy", windSpeed: 10, humidity: 55 },
    attendance: 5500,
    broadcast: { network: "NFHS Network" },
    matchupDisplay: "SERR @ DLS",
  },
  {
    id: "hs-007",
    league: "HighSchool",
    homeTeamId: "hs-img-academy",
    awayTeamId: "hs-st-thomas",
    date: "2024-09-20",
    kickoffTime: "19:00",
    season: "2024",
    week: 4,
    gameType: "regular",
    status: "final",
    score: { home: 35, away: 28, quarters: { q1: { home: 7, away: 7 }, q2: { home: 14, away: 7 }, q3: { home: 7, away: 7 }, q4: { home: 7, away: 7 } } },
    venue: "IMG Academy Stadium",
    city: "Bradenton, FL",
    weather: { temperature: 85, condition: "cloudy", windSpeed: 8, humidity: 75 },
    attendance: 3500,
    broadcast: { network: "ESPNU" },
    matchupDisplay: "STA @ IMG",
  },
  {
    id: "hs-008",
    league: "HighSchool",
    homeTeamId: "hs-miami-central",
    awayTeamId: "hs-miami-northwestern",
    date: "2024-10-18",
    kickoffTime: "19:30",
    season: "2024",
    week: 8,
    gameType: "regular",
    status: "final",
    score: { home: 21, away: 20, quarters: { q1: { home: 7, away: 7 }, q2: { home: 0, away: 6 }, q3: { home: 7, away: 0 }, q4: { home: 7, away: 7 } } },
    venue: "Traz Powell Stadium",
    city: "Miami, FL",
    weather: { temperature: 82, condition: "clear", windSpeed: 5, humidity: 70 },
    attendance: 8000,
    broadcast: { network: "NFHS Network" },
    matchupDisplay: "MNW @ MCR",
  },
  {
    id: "hs-009",
    league: "HighSchool",
    homeTeamId: "hs-buford",
    awayTeamId: "hs-collins-hill",
    date: "2024-11-08",
    kickoffTime: "19:30",
    season: "2024",
    week: 11,
    gameType: "playoff",
    status: "final",
    score: { home: 28, away: 14, quarters: { q1: { home: 7, away: 7 }, q2: { home: 14, away: 0 }, q3: { home: 0, away: 0 }, q4: { home: 7, away: 7 } } },
    venue: "Tom Riden Stadium",
    city: "Buford, GA",
    weather: { temperature: 55, condition: "clear", windSpeed: 10, humidity: 50 },
    attendance: 8000,
    broadcast: { network: "GPB Sports" },
    matchupDisplay: "CHE @ BUF",
  },
  {
    id: "hs-010",
    league: "HighSchool",
    homeTeamId: "hs-grayson",
    awayTeamId: "hs-mill-creek",
    date: "2024-10-25",
    kickoffTime: "19:30",
    season: "2024",
    week: 9,
    gameType: "regular",
    status: "final",
    score: { home: 35, away: 31, quarters: { q1: { home: 7, away: 14 }, q2: { home: 14, away: 7 }, q3: { home: 7, away: 3 }, q4: { home: 7, away: 7 } } },
    venue: "Grayson Stadium",
    city: "Loganville, GA",
    weather: { temperature: 58, condition: "cloudy", windSpeed: 8, humidity: 55 },
    attendance: 9500,
    broadcast: { network: "GPB Sports" },
    matchupDisplay: "MCH @ GRAY",
  },
]

// ---------------------------------------------------------------------------
// Helper Functions
// ---------------------------------------------------------------------------

/**
 * Get a game by its ID
 */
export function getGameById(gameId: string): Game | undefined {
  return mockGames.find((g) => g.id === gameId)
}

/**
 * Get all games for a specific team
 */
export function getGamesForTeam(teamId: string): Game[] {
  return mockGames.filter(
    (g) => g.homeTeamId === teamId || g.awayTeamId === teamId
  )
}

/**
 * Get all games for a specific week
 */
export function getGamesByWeek(season: string, week: number): Game[] {
  return mockGames.filter((g) => g.season === season && g.week === week)
}

/**
 * Get all games with a specific status
 */
export function getGamesByStatus(status: GameStatus): Game[] {
  return mockGames.filter((g) => g.status === status)
}

/**
 * Get all games for a specific season
 */
export function getGamesBySeason(season: string): Game[] {
  return mockGames.filter((g) => g.season === season)
}

/**
 * Get all unique seasons available in the data
 */
export function getAvailableSeasons(): string[] {
  return [...new Set(mockGames.map((g) => g.season))].sort().reverse()
}

/**
 * Get games by league
 */
export function getGamesByLeague(league: GameLeague): Game[] {
  return mockGames.filter((g) => g.league === league)
}

/**
 * Get all unique leagues available in the data
 */
export function getAvailableLeagues(): GameLeague[] {
  return [...new Set(mockGames.map((g) => g.league))] as GameLeague[]
}
